### ISSUE TITLE
Setup a new kanban board

### ISSUE THREAD

**Issue by stephenkati** [stephenkati/JavaScript-capstone-group-project#21]
We are a group of 2 students.
We have setup the kanban board below.
https://github.com/stephenkati/JavaScript-capstone-group-project/projects/1

**Comment by KayLemba** [comment]
Hi @stephenkati  👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.

- It says in the project requirements that:

- Cards should be assigned to team members in a fair way:

- Students needed to decide who is Student A, Student B, Student C. So each card with Student A in its title should always be assigned to the same student (and analogical for other students).
All cards with group task in the title should be assigned to someone (it does not matter to whom as students had freedom with that).






Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by mckent05** [comment]
Hi team, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.
![almost there](https://user-images.githubusercontent.com/73607512/207265397-5ef597f5-a50c-49b4-8f07-7548b0520e98.gif)


 ## Highlights
- You have done well setting up your Kanban 


 ## Required Changes ♻️
- Like the previous reviewer said, Please ensure that all cards in your Kanban board have been properly assigned to a group menber. This is how a properly assigned card should look:
<img width="372" alt="sSdve" src="https://user-images.githubusercontent.com/73607512/224703440-c812fecd-1c13-4f91-ac06-2317a89cc09f.png">

_Check the comments under the review._

## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your code.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @stephenkati and @Matthieu96Code,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
